# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, default='88888', max_digits=7, verbose_name='价格')),
                ('market_price', models.DecimalField(decimal_places=2, default=99999, max_digits=7, verbose_name='市场价')),
                ('pub', models.CharField(max_length=30, verbose_name='出版社')),
            ],
        ),
    ]
